### ISSUE TITLE
Explain nested defaults in the readme

### ISSUE THREAD

**Issue by danijar** [danijar/definitions#10]
It is not obvious that the empty default at the outer level is needed:

``` yaml
type: dict
mapping:
  key:
    default: 42
default: {}
```
